### PR TITLE
Initial Architecture Documentation and Decisions

### PR DESCRIPTION
**Pull request by Lugarun**
I thought that this would be a good place to document our architecture decisions.

I have started with a rough diagram of the different components that I could come up with as a starting point.
diagram

For this pull request, we should come to consensus on and document:
- [ ] An outline our architecture
- [ ] The responsibilities of each service
- [ ] Initial definitions of the interfaces between services

### CODE REVIEW

**Comment by Lugarun** [comment]
I'm not happy with 'Match Maker' yet but I also don't know how to break it down nicely.
Right now it is responsible for:
- scheduling matches
- ranking players
- running matches
- collecting and storing match results

Maybe we should separate the match runner from the match maker?

**Comment by Lugarun** [comment]
Here I have broken ranking and game queuing/scheduling out of the  match maker into a 'ranker'.
diagram

**Comment by Lugarun** [comment]
I have updated the architecture documentation and diagrams based on our last discussion.
overview
run_game

**Review by japorized — APPROVED** [review]
LGTM

**Review by mosiman — APPROVED** [review]
LGTMMMMMMMMMMM

**Pull request merged**
